version: '2'

services:
  postgresql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: diamond
      POSTGRES_USER: diamond
      POSTGRES_DB: diamond

  redis:
    image: redis

  web:
    build: .
    env_file:
      - .env
    command: ['web']
    ports:
      - 8080:8080
    depends_on:
      - postgresql
      - redis

  worker:
    build: .
    env_file:
      - .env
    command: ['worker']
    depends_on:
      - postgresql
      - redis
