version: '2'
services:
  db:
    image: postgres

  cache:
    image: redis

  web:
    build: .
    env_file:
      - .env
    command: gunicorn diamond:app -b 0.0.0.0:8080
    ports:
      - 8080:8080
    depends_on:
      - db
      - cache
